version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "dev.rikka.shizuku"
      - dependency-type: "plugin"
        group: "com.android.tools.build"
        name: "gradle"
        versions: []