version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    target-branch: "main"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "dev.rikka.shizuku"

  - package-ecosystem: "gradle"
    directory: "/app"
    target-branch: "development"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "com.android.tools.build:gradle"
        dependency-type: "plugin"
        versions: []